### PR TITLE
fix: set correct Content-Type

### PR DESCRIPTION
**Pull request by PJGitLan**
Content-Type was not set correctly for postCount() and postSearch()

### CODE REVIEW

**Review by thjaeckle — APPROVED** [review]
LGTM, thanks a lot @PJGitLan

**Comment by PJGitLan** [comment]
@thjaeckle Do you have a timeline for the next release with this fix?

**Comment by thjaeckle** [comment]
@PJGitLan oh, it should have been in 3.5.4 - but I see we did not publish that to npm ..
Sorry for that .. will prepare a 3.5.4 bugfix release

**Comment by PJGitLan** [comment]
> @PJGitLan oh, it should have been in 3.5.4 - but I see we did not publish that to npm .. Sorry for that .. will prepare a 3.5.4 bugfix release

No problem and thank you!

**Pull request merged**
